### ISSUE TITLE
streamlit_sortables won't import

### ISSUE THREAD

**Issue by doughagey** [ohtaman/streamlit-sortables#11]
When importing streamlit-sortables from a python file other than the main script (app.py) I get a TypeEror: 'type' object is not subscriptable 

'from streamlit_sortables import sort_items' is all that I have added to the existing script. I am running python 3.8.13 with Streamlit 1.22.0 and tried 1.15 as well. When the import is removed the app runs normally.

<img width="706" alt="Screenshot 2023-05-18 at 5 35 51 PM" src="https://github.com/ohtaman/streamlit-sortables/assets/58292241/e46ae1af-29c8-4985-bc11-e7cd3f225502">

**Comment by mdebic** [comment]
Hi, ran into the same issue today. Using Python 3.10 fixed it for me.

**Comment by JimmyDore** [comment]
Working on a python 3.8 project, it seems the version 0.2.0 of the package is not compatible anymore. Installing an old version worked for me : `pip install streamlit-sortables==0.1.3` ( but it's obviously not a long run solution, won't be able to install any new upgrades )

**Comment by ohtaman** [comment]
I have confirmed that it works with Python 3.9 specified in pyproject.toml, so I am closing this.
