### ISSUE TITLE
Text font and widget text color background color not consistent with app

### ISSUE THREAD

**Issue by neldivad** [ohtaman/streamlit-sortables#12]
![Capture](https://github.com/ohtaman/streamlit-sortables/assets/59020919/f951bc17-70c6-4fd8-8cca-3927f3f64c95)
Needs a way to customize the text size, font, and color to match the current streamlit template.

**Comment by nickgreengithub** [comment]
Yes, deal breaker for my use case unfortunately -- would be great!

**Comment by ohtaman** [comment]
#18 allows for customizing the styles.
